# Generated by Django 3.1.1 on 2020-09-12 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0003_auto_20200909_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_admitted', models.DateField(auto_now_add=True, help_text='Date of Registration', verbose_name='Date Issued')),
                ('code_no', models.CharField(db_index=True, default='VJlKr', max_length=255, unique=True, verbose_name='Registration No')),
                ('surname', models.CharField(max_length=30, verbose_name='Surname')),
                ('middle_name', models.CharField(max_length=30, verbose_name='Middle Name')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('phone_number', models.CharField(max_length=14, verbose_name='Phone Number')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Email Address')),
                ('occupation', models.CharField(max_length=255, verbose_name='Occupation')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2, verbose_name='Sex')),
                ('Age', models.IntegerField(verbose_name='Age')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('marital_status', models.CharField(choices=[('M', 'Married'), ('S', 'Single')], max_length=2, verbose_name='Marital Status')),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, verbose_name='Blood Group')),
                ('genotype', models.CharField(choices=[('AO', 'AO'), ('AA', 'AA'), ('BO', 'BO'), ('BB', 'BB'), ('AB', 'AB'), ('OO', 'OO')], max_length=2, verbose_name='GENOTYPE')),
                ('hospitals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_no', models.CharField(default='2wPPQ', max_length=255, verbose_name='Registration No')),
                ('date_admitted', models.DateField(help_text='Date patient was admitted', verbose_name='Date Admitted')),
                ('reffered_by', models.CharField(max_length=255, verbose_name='Reffered By')),
                ('doctor', models.CharField(max_length=255, verbose_name='Doctor or Surgeon')),
                ('ward', models.CharField(max_length=255, verbose_name='Ward or Clinic')),
                ('date_discharged', models.DateField(blank=True, default=None, help_text='Date of discharge', null=True, verbose_name='Date Discharged')),
                ('discharged_to', models.CharField(max_length=255, verbose_name='Discharged To')),
                ('condition', models.TextField(verbose_name='Patient Condition on discharge')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient', verbose_name='patients')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date of diagnosis')),
                ('diagnosis', models.TextField(verbose_name='Report on diagnosis')),
                ('code_no', models.CharField(help_text='Alphanumeric length of 5.', max_length=5, verbose_name='Patient code No')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient', verbose_name='patients')),
            ],
        ),
    ]
