# Generated by Django 3.1.1 on 2020-09-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date of diagnosis')),
                ('diagnosis', models.TextField(verbose_name='Report on diagnosis')),
                ('code_no', models.CharField(help_text='Alphanumeric length of 5.', max_length=5, verbose_name='Patient code No')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_admitted', models.DateField(help_text='Date patient was admitted', verbose_name='Date Admitted')),
                ('reffered_by', models.CharField(max_length=255, verbose_name='Reffered By')),
                ('doctor', models.CharField(max_length=255, verbose_name='Doctor or Surgeon')),
                ('ward', models.CharField(max_length=255, verbose_name='Ward or Clinic')),
                ('date_discharged', models.DateTimeField(blank=True, default=None, help_text='Date of discharge', null=True, verbose_name='Date Discharged')),
                ('discharged_to', models.CharField(max_length=255, verbose_name='Discharged To')),
                ('condition', models.TextField(verbose_name='Patient Condition on discharge')),
            ],
        ),
    ]
