# Generated by Django 3.1.1 on 2020-09-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(default='Hospital Name', max_length=255, null=True),
        ),
    ]
