# Generated by Django 3.0.6 on 2020-09-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='postal_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(default='Hospital Name', max_length=255, null=True),
        ),
    ]
