# Generated by Django 3.1.1 on 2020-09-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20200908_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(default='Hosipital Name', max_length=255, null=True),
        ),
    ]
